# Generated by Django 3.2.3 on 2021-06-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clareza', models.CharField(max_length=15)),
                ('originalidade', models.CharField(max_length=15)),
                ('design', models.CharField(max_length=15)),
                ('rigor', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True)),
                ('apelido', models.CharField(max_length=20, null=True)),
                ('telefone', models.IntegerField(default=9, null=True)),
                ('email', models.EmailField(default='@hotmail.com', max_length=40, null=True)),
                ('data_nascimento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('pergunta', models.CharField(max_length=80)),
                ('resposta', models.CharField(max_length=50)),
                ('pontos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('tempo', models.IntegerField(default=0)),
                ('pontuaçao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pontos', models.IntegerField(default=0)),
                ('quizz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.quizz')),
            ],
        ),
    ]
