# Generated by Django 3.2.3 on 2021-06-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210604_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='ponto',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
