# Generated by Django 3.2.3 on 2021-06-04 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210604_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='resposta',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='quizz',
            name='pergunta',
            field=models.ManyToManyField(to='website.Pergunta'),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=30)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pergunta')),
            ],
        ),
    ]
