# Generated by Django 3.2.3 on 2021-06-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210604_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='resposta',
        ),
        migrations.AddField(
            model_name='resposta',
            name='respostas',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
    ]
