# Generated by Django 3.2.3 on 2021-06-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210604_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='respostas10',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='respostas2',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='respostas3',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='respostas4',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='respostas5',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='respostas6',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='respostas7',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='respostas8',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='respostas9',
        ),
    ]
