# Generated by Django 3.2.3 on 2021-06-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210604_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='respostas1',
            new_name='respostas',
        ),
    ]
