# Generated by Django 3.2.4 on 2021-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_resposta_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='Pontos_clareza',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='Pontos_design',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='Pontos_originalidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='Pontos_rigor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='clareza',
            field=models.CharField(choices=[('PÉSSIMO', 'PÉSSIMO'), ('MAU', 'MAU'), ('BOM', 'BOM'), ('MUITO BOM', 'MUITO BOM'), ('EXCELENTE', 'EXCELENTE')], default='BOM', max_length=10),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='design',
            field=models.CharField(choices=[('PÉSSIMO', 'PÉSSIMO'), ('MAU', 'MAU'), ('BOM', 'BOM'), ('MUITO BOM', 'MUITO BOM'), ('EXCELENTE', 'EXCELENTE')], default='BOM', max_length=10),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='originalidade',
            field=models.CharField(choices=[('PÉSSIMO', 'PÉSSIMO'), ('MAU', 'MAU'), ('BOM', 'BOM'), ('MUITO BOM', 'MUITO BOM'), ('EXCELENTE', 'EXCELENTE')], default='BOM', max_length=10),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='rigor',
            field=models.CharField(choices=[('PÉSSIMO', 'PÉSSIMO'), ('MAU', 'MAU'), ('BOM', 'BOM'), ('MUITO BOM', 'MUITO BOM'), ('EXCELENTE', 'EXCELENTE')], default='BOM', max_length=10),
        ),
    ]
