# Generated by Django 3.2.4 on 2021-06-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210617_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='significância',
            field=models.CharField(choices=[('PÉSSIMO', 'PÉSSIMO'), ('MAU', 'MAU'), ('BOM', 'BOM'), ('MUITO BOM', 'MUITO BOM'), ('EXCELENTE', 'EXCELENTE')], default='BOM', max_length=10),
        ),
    ]
