# Generated by Django 3.2.4 on 2021-06-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_comentario_significância'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comment',
            field=models.TextField(default='Escreve aqui o teu comentário', max_length=200),
        ),
    ]
