# Generated by Django 3.2.4 on 2021-06-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_comentario_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comment',
            new_name='comentário',
        ),
    ]
