# Generated by Django 3.2.4 on 2021-06-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_contato_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
