# Generated by Django 3.2.5 on 2021-07-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_contato_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='animal',
            field=models.CharField(choices=[('Alce', 'Alce'), ('Chita', 'Chita'), ('Cão', 'Cão'), ('Gato', 'Gato'), ('Leão', 'Leão'), ('Leopardo', 'Leopardo'), ('Orca', 'Orca'), ('Tigre', 'Tigre'), ('Touro', 'Touro'), ('Tubarão', 'Tubarão')], default='Cao', max_length=10),
        ),
    ]
